Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  #config.vm.network "forwarded_port", guest: 80, host: 8888, host_ip: "127.0.0.1"
  config.vm.hostname = "gitlab-server"
  config.vm.network "private_network", ip: "192.168.2.90"
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end
end