Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  #config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  #config.vm.provision "shell", path: "provision.sh"
  config.vm.hostname = "gitlab-server"
  config.vm.network "private_network", ip: "192.168.2.90"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

end